### ISSUE TITLE
Outdated Validation for Snapshot Schema

### ISSUE THREAD

**Issue by greenlucid** [gnosis/zodiac-safe-app#194]
**Describe the bug**

Cannot use reality module because `Your snapshot settings file is invalid`

**To Reproduce**

1. Create a snapshot space
2. Create a safe
3. Try to add zodiac reality module
4. Write ens
5. `Your snapshot settings file is invalid`

**Expected behavior**

This error to not appear.

I would also expect the error to be automatically solvable (like, providing a button to a tx or signature that will automatically set an unbroken schema).

**Screenshots / logs**

![image](https://user-images.githubusercontent.com/40367733/223714995-f319e06f-e849-4c21-8f03-936137d03d10.png)

![image](https://user-images.githubusercontent.com/40367733/223715098-ade30bfe-ed71-4401-a9bc-bf87959a03a9.png)

**Relevant environment details:**

not relevant.

**Additional context**

Snapshot added moderators to the schema recently.
https://github.com/snapshot-labs/snapshot.js/blob/d76a688721f5302771f3fb220c07c3488c8cf50d/src/schemas/space.json

**Comment by manboy-eth** [comment]
Thank you!

Solved in #197
