### ISSUE TITLE
Native asset always displayed as ETH

### ISSUE THREAD

**Issue by auryn-macmillan** [gnosis/zodiac-safe-app#46]
![image](https://user-images.githubusercontent.com/8453294/135830106-156f5ffd-c75e-4aa3-8dc0-55a3075c0530.png)
The native asset is always written as "ETH", even though it has different names on different networks.
e.g. xDai on the xDai network, MATIC on Polygon, etc.

**Comment by carlosfebres** [comment]
@auryn-macmillan I remember to have solved this, I'll give it another look
