### ISSUE TITLE
[Reality Module] Set up monitoring service

### ISSUE THREAD

**Issue by manboy-eth** [gnosis/zodiac-safe-app#86]
Let the user set up monitoring service via Tenderly.

- [ ] Figuring out what parameters we need.
- [ ] Get the parameters from the user in the monitoring step.
- [ ] Set up monitoring via the Tenderly API (remember Gnosis is going to provide some level of monitoring for free for the user).

**Comment by manboy-eth** [comment]
Some places to start:
https://docs.tenderly.co/web3-actions/how-to-handle-on-chain-events
https://docs.tenderly.co/alerts/alerting
https://docs.tenderly.co/alerts/creating-an-alert
https://docs.tenderly.co/alerts/alerting/rule-types

We need to figure out what events we want to monitor. For starters, probably:
- New questions for the oracle (Reality.eth)
- Answers to the question (Reality.eth)
- When a question enters Cooldown
- ...

**Comment by auryn-macmillan** [comment]
> I am not a fan of the centralized approach, where we are responsible for notifying users and holding their information.
Yeah, I'm also not a fan of this approach. Ideal case would be if users could provide an API key / otherwise authenticate our app with some existing service and then we simply set up the notifications via an API.

Let me dig around and see if I can come up with any other good solutions.

**Comment by auryn-macmillan** [comment]
@manboy-eth, it looks like the Open Zeppelin API should allow us to set up notifications on behalf of users. Users would need to provide their OZ API key, along with addresses / keys / webhooks for the channels they would like notifications pushed to.

https://docs.openzeppelin.com/defender/sentinel-api-reference

**Comment by manboy-eth** [comment]
> @manboy-eth, it looks like the Open Zeppelin API should allow us to set up notifications on behalf of users. Users would need to provide their OZ API key, along with addresses / keys / webhooks for the channels they would like notifications pushed to.
> 
> https://docs.openzeppelin.com/defender/sentinel-api-reference

Nice. Yes, this looks promising :D

**Comment by manboy-eth** [comment]
Since the monitoring service we are using does not support calls directly from the browser (see: https://forum.openzeppelin.com/t/calling-the-defender-api-from-the-browser/31967), we need to use some sort of backend to do this. The plan is to do it the same way as @jfschwarz has done here: https://github.com/gnosis/zodiac-pilot/tree/main/fork-api. Therefore we will need to restructure the directory layout to accommodate this.
